title: "Portfólio de Ruan Rolim"
description: >- # Este é o subtítulo do site.
  Bem-vindo ao meu portfólio! Aqui você encontra meus projetos, habilidades e informações para contato.
baseurl: "" # Não altere se estiver usando o repositório raiz
url: "https://RuanT-310.github.io" # Atualize para o seu URL do GitHub Pages

theme: minima # Ativa o tema Minima

# Configurações extras
plugins:
  - jekyll-feed # Para feeds RSS

# Links para contato
social_links:
  github: RuanT-310
  linkedin: SeuPerfilLinkedIn
  email: SeuEmail@email.com
